#!/bin/bash

git clone https://gitlab.com/romanov73/example-jpa.git
./example-jpa/gradlew build
systemctl postgres disable
systemctl postgres stop
docker build -t file -f FileDocker .
docker run file
